import { useEffect, useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { getTripById, togglePackingItem, updateTripSaved } from '../services/tripService';
import { useToast } from '../context/ToastContext';
import '../styles/TripResult.css';

const CATEGORY_LABELS = {
  DOCUMENTS: 'Documents',
  CLOTHING: 'Clothing',
  ELECTRONICS: 'Electronics',
  TOILETRIES: 'Toiletries',
  HEALTH: 'Health',
  MISC: 'Miscellaneous',
};

const CATEGORY_ICONS = {
  DOCUMENTS: '📄',
  CLOTHING: '👕',
  ELECTRONICS: '🔌',
  TOILETRIES: '🧴',
  HEALTH: '💊',
  MISC: '🎒',
};

export default function TripResult() {
  const { tripId } = useParams();
  const navigate = useNavigate();
  const { showToast } = useToast();

  const [trip, setTrip] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const [savingFlag, setSavingFlag] = useState(false);
  const [activeTab, setActiveTab] = useState('itinerary');

  useEffect(() => {
    setLoading(true);
    getTripById(tripId)
      .then(setTrip)
      .catch(() => setError('Could not load this trip.'))
      .finally(() => setLoading(false));
  }, [tripId]);

  async function handleToggleSaved() {
    if (!trip) return;
    setSavingFlag(true);
    try {
      const updated = await updateTripSaved(trip.id, !trip.saved);
      setTrip(updated);
      showToast(updated.saved ? 'Trip saved' : 'Trip unsaved', 'success');
    } finally {
      setSavingFlag(false);
    }
  }

  async function handleTogglePackingItem(item) {
    const updatedItem = await togglePackingItem(trip.id, item.id, !item.checked);
    setTrip((prev) => ({
      ...prev,
      packingList: prev.packingList.map((pi) => (pi.id === updatedItem.id ? updatedItem : pi)),
    }));
  }

  if (loading) {
    return (
      <div className="container trip-result-page">
        <div className="skeleton skeleton-card" style={{ height: 140, marginBottom: 24 }} />
        <div className="skeleton skeleton-line" style={{ width: 220, marginBottom: 20 }} />
        <div className="skeleton skeleton-card" style={{ marginBottom: 16 }} />
        <div className="skeleton skeleton-card" style={{ marginBottom: 16 }} />
      </div>
    );
  }

  if (error || !trip) {
    return (
      <div className="container">
        <div className="card empty-state fade-in">
          <div className="empty-state-icon">😕</div>
          <p>{error || 'Trip not found.'}</p>
          <button className="btn btn-primary" onClick={() => navigate('/my-trips')}>Back to My Trips</button>
        </div>
      </div>
    );
  }

  const groupedPacking = (trip.packingList || []).reduce((groups, item) => {
    const key = item.category || 'MISC';
    if (!groups[key]) groups[key] = [];
    groups[key].push(item);
    return groups;
  }, {});

  const checkedCount = (trip.packingList || []).filter((i) => i.checked).length;
  const totalCount = (trip.packingList || []).length;
  const packingPercent = totalCount === 0 ? 0 : Math.round((checkedCount / totalCount) * 100);

  return (
    <div className="container trip-result-page">
      <div className="trip-result-header card fade-in">
        <div>
          <div className="trip-result-title-row">
            <h1>{trip.destination}</h1>
            {trip.aiGenerated ? (
              <span className="ai-badge" title="Generated by Google Gemini">✨ AI-Generated</span>
            ) : (
              <span className="ai-badge ai-badge-standard" title="Generated by TripWise's built-in planner">🧩 Standard</span>
            )}
          </div>
          <div className="trip-result-meta">
            <span className="badge badge-primary">📆 {trip.days} days</span>
            <span className="badge badge-accent">💰 ₹{trip.budget}</span>
            <span className="badge badge-secondary">🎒 {trip.travelType}</span>
          </div>
          {trip.interests?.length > 0 && (
            <p className="trip-result-interests">
              Interests: {trip.interests.map((i) => i[0].toUpperCase() + i.slice(1)).join(', ')}
            </p>
          )}
        </div>
        <button className="btn btn-outline" onClick={handleToggleSaved} disabled={savingFlag}>
          {trip.saved ? '★ Saved' : '☆ Save Trip'}
        </button>
      </div>

      <div className="trip-tabs">
        <button
          className={`trip-tab ${activeTab === 'itinerary' ? 'active' : ''}`}
          onClick={() => setActiveTab('itinerary')}
        >
          🗓️ Day-wise Itinerary
        </button>
        <button
          className={`trip-tab ${activeTab === 'packing' ? 'active' : ''}`}
          onClick={() => setActiveTab('packing')}
        >
          🧳 Packing Checklist ({checkedCount}/{totalCount})
        </button>
      </div>

      {activeTab === 'itinerary' ? (
        <div className="itinerary-list fade-in-stagger">
          {trip.itinerary?.map((day) => (
            <div className="card itinerary-day" key={day.id}>
              <h3>{day.title}</h3>
              <ul className="activity-list">
                {day.activities.map((activity) => (
                  <li key={activity.id} className="activity-item">
                    <span className={`badge badge-${badgeVariant(activity.category)}`}>{activity.category}</span>
                    <span>{activity.description}</span>
                  </li>
                ))}
              </ul>
            </div>
          ))}
        </div>
      ) : (
        <>
          <div className="card packing-progress fade-in">
            <div className="packing-progress-header">
              <span>Packing progress</span>
              <span>{packingPercent}%</span>
            </div>
            <div className="progress-track">
              <div className="progress-fill" style={{ width: `${packingPercent}%` }} />
            </div>
          </div>

          <div className="packing-list fade-in-stagger">
            {Object.entries(groupedPacking).map(([category, items]) => (
              <div className="card packing-category" key={category}>
                <h3>{CATEGORY_ICONS[category] || '🎒'} {CATEGORY_LABELS[category] || category}</h3>
                <ul className="packing-items">
                  {items.map((item) => (
                    <li key={item.id} className="packing-item">
                      <label>
                        <input
                          type="checkbox"
                          checked={item.checked}
                          onChange={() => handleTogglePackingItem(item)}
                        />
                        <span className={item.checked ? 'checked' : ''}>{item.name}</span>
                      </label>
                      {item.tip && <p className="packing-tip">💡 {item.tip}</p>}
                    </li>
                  ))}
                </ul>
              </div>
            ))}
          </div>
        </>
      )}
    </div>
  );
}

function badgeVariant(category) {
  if (category === 'FOOD') return 'accent';
  if (category === 'EXPERIENCE') return 'secondary';
  return 'primary';
}
